/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;
import panels.Home;
import panels.Newstudent;

import panels.Search;
import panels.enroll;

/**
 *
 * @author Natasha
 */
public class Main_Menu extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    Home p1;
    Newstudent p2;
    enroll p3;
    Search p4;

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
        

        p1 = new Home();
        p2 = new Newstudent();
        p3 = new enroll();
        p4 = new Search();
        pnlprinciple.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        pnlprinciple.add(p1, c);
        c.gridx = 0;
        c.gridy = 0;
        pnlprinciple.add(p2, c);
        c.gridx = 0;
        c.gridy = 0;
        pnlprinciple.add(p3, c);
        c.gridx = 0;
        c.gridy = 0;

        pnlprinciple.add(p4, c);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }

    public void gencode(String sl) {
        display.setText(sl);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmenu = new javax.swing.JPanel();
        jButton2logout = new javax.swing.JButton();
        jButton3home = new javax.swing.JButton();
        jButton4add = new javax.swing.JButton();
        jButton5enroll = new javax.swing.JButton();
        jButton6search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlprinciple = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlmenu.setBackground(new java.awt.Color(0, 102, 204));
        pnlmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2logout.setBackground(new java.awt.Color(102, 102, 102));
        jButton2logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2logout.setForeground(new java.awt.Color(51, 51, 51));
        jButton2logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/User-Interface-Logout-icon.png"))); // NOI18N
        jButton2logout.setText("  Log out");
        jButton2logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2logoutActionPerformed(evt);
            }
        });
        pnlmenu.add(jButton2logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 80));

        jButton3home.setBackground(new java.awt.Color(102, 102, 102));
        jButton3home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3home.setForeground(new java.awt.Color(51, 51, 51));
        jButton3home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/home-icon.png"))); // NOI18N
        jButton3home.setText(" HOME       ");
        jButton3home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3homeActionPerformed(evt);
            }
        });
        pnlmenu.add(jButton3home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 80));

        jButton4add.setBackground(new java.awt.Color(102, 102, 102));
        jButton4add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4add.setForeground(new java.awt.Color(51, 51, 51));
        jButton4add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Users-Student-icon.png"))); // NOI18N
        jButton4add.setText("STUDENT ");
        jButton4add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4addActionPerformed(evt);
            }
        });
        pnlmenu.add(jButton4add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 80));

        jButton5enroll.setBackground(new java.awt.Color(102, 102, 102));
        jButton5enroll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5enroll.setForeground(new java.awt.Color(51, 51, 51));
        jButton5enroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Science-Classroom-icon.png"))); // NOI18N
        jButton5enroll.setText("ENROLL  ");
        jButton5enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5enrollActionPerformed(evt);
            }
        });
        pnlmenu.add(jButton5enroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 80));

        jButton6search.setBackground(new java.awt.Color(102, 102, 102));
        jButton6search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6search.setForeground(new java.awt.Color(51, 51, 51));
        jButton6search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/search-icon.png"))); // NOI18N
        jButton6search.setText("SEARCH      ");
        jButton6search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6searchActionPerformed(evt);
            }
        });
        pnlmenu.add(jButton6search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/online-icon.png"))); // NOI18N
        pnlmenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        pnlmenu.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("User:");
        pnlmenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(pnlmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 630));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setText("ABC University Student Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 60));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 90));

        pnlprinciple.setBackground(new java.awt.Color(255, 255, 255));
        pnlprinciple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlprinciple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 1190, 620));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2logoutActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Do You Want To Logout", "Logout", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButton2logoutActionPerformed

    private void jButton3homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3homeActionPerformed

        //pnlmenu.setVisible(true);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_jButton3homeActionPerformed

    private void jButton4addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4addActionPerformed

        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);

    }//GEN-LAST:event_jButton4addActionPerformed

    private void jButton5enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5enrollActionPerformed

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);

    }//GEN-LAST:event_jButton5enrollActionPerformed

    private void jButton6searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6searchActionPerformed

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);

        //        Search s = new Search();
        //        s.setSize(620, 470);
        //       jPanel2.add(s);
    }//GEN-LAST:event_jButton6searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel display;
    private javax.swing.JButton jButton2logout;
    private javax.swing.JButton jButton3home;
    private javax.swing.JButton jButton4add;
    private javax.swing.JButton jButton5enroll;
    private javax.swing.JButton jButton6search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JPanel pnlprinciple;
    // End of variables declaration//GEN-END:variables
}
