/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class enroll extends javax.swing.JPanel {
Connection con;
    /**
     * Creates new form enroll
     */
    public enroll() {
        initComponents();
        DBconnection c= new DBconnection();
        con=c.getconnection();
    }
    
    
    
public void clear(){

studentid.setText("");
nic.setText("");
fullname.setText("");
initial.setText("");
jCombocourse.setSelectedItem("None");
jComboduration.setSelectedItem("None");
batch.setText("");
jCombobatch.setSelectedItem("None");
ugraduatefee.setText("");
studentid1.setText("");
nic1.setText("");
fullname1.setText("");
initial1.setText("");
jCombocourse1.setSelectedItem("None");
jComboduration1.setSelectedItem("None");
batch1.setText("");
jCombobatch1.setSelectedItem("None");
ugraduatefee1.setText("");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCombocourse = new javax.swing.JComboBox<>();
        fullname = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboduration = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        batch = new javax.swing.JTextField();
        jCombobatch = new javax.swing.JComboBox<>();
        initial = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ugraduatefee = new javax.swing.JTextField();
        jButton3save1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        studentid1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        nic1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        fullname1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        initial1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCombocourse1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboduration1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        batch1 = new javax.swing.JTextField();
        jCombobatch1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        ugraduatefee1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 44)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 204));
        jLabel20.setText("STUDENT ENROLLMENT FOR COURSES");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 930, 90));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Student Uni Id");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Nic/Passport Number");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Full name");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setText("Enrolling Course Name");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));

        jCombocourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Master of Business Administration - Cardiff Metropolitan University (UK)", "MSc in Information Technology - Cardiff Metropolitan University (UK)", "International Business Masters in Law (LLM) - Cardiff Metropolitan University (UK)", "MSc Strategic Marketing - Cardiff Metropolitan University (UK)", "Master of Business Administration - University of Sunderland (UK)", "Post Graduate Diploma in Business Management ", "Master of Science (Hons) in Construction Project Management", "Master of Science (Hons) in Quantity Surveying", "MSc in Project Management", "MSc in Psychology", " " }));
        jPanel5.add(jCombocourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 270, 30));

        fullname.setEditable(false);
        jPanel5.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, 30));

        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicKeyTyped(evt);
            }
        });
        jPanel5.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 270, 30));

        studentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentidKeyReleased(evt);
            }
        });
        jPanel5.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 270, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("Duration");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 210, 30));

        jComboduration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1 Years part time", "1 Years Full time" }));
        jPanel5.add(jComboduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 270, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("Batch");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 210, 30));
        jPanel5.add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 30, 30));

        jCombobatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Sunday 8.00 am to 5.00 pm", "Saturday  8.00 am to 5.00 pm", "Weekdays 8.00 am to 5.00 pm(Full time Students Only)" }));
        jPanel5.add(jCombobatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 230, 30));

        initial.setEditable(false);
        jPanel5.add(initial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 270, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("Name With Initials");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Course Fee");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 210, 30));
        jPanel5.add(ugraduatefee, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 270, 30));

        jButton3save1.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton3save1.setForeground(new java.awt.Color(0, 102, 204));
        jButton3save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Save-as-icon.png"))); // NOI18N
        jButton3save1.setText("Save");
        jButton3save1.setAutoscrolls(true);
        jButton3save1.setOpaque(false);
        jButton3save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3save1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 90));

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Text-Edit-icon.png"))); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 250, 90));

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Close-2-icon.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 250, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("To search or delete individual enrollment type the student number in student uni id field");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 540, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Actions-edit-clear-icon.png"))); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 250, 90));

        jTabbedPane1.addTab("Poster Graduate", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Text-Edit-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 250, 90));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 204));
        jLabel27.setText("Student Uni Id");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 30));

        studentid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentid1KeyReleased(evt);
            }
        });
        jPanel4.add(studentid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 270, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 204));
        jLabel26.setText("Nic/Passport Number");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 30));

        nic1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nic1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nic1KeyTyped(evt);
            }
        });
        jPanel4.add(nic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 270, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 204));
        jLabel25.setText("Full name");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 30));

        fullname1.setEditable(false);
        jPanel4.add(fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 204));
        jLabel24.setText("Name With Initials");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 30));

        initial1.setEditable(false);
        jPanel4.add(initial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 270, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 204));
        jLabel23.setText("Enrolling Course Name");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));

        jCombocourse1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "ICBT HND in Biomedical Science", "ICBT HND in Biomedical Engineering", "ICBT HND in Automotive Engineering", "ICBT HND in Civil EngineeringICBT HND in Electrical - Electronic Engineering", "ICBT HND Mechatronics Engineering", "ICBT HND in Mechanical Engineering", "ICBT HND in Telecommunication & Electronics Engineering", "ICBT HND in Quantity Surveying & Built Environment", "ICBT HND in Psychology", "ICBT Dual HND Software Engineering + Computing", "ICBT HND Business Management ( Finance MarketingHRM)", "BSc (Hons) Psychology - Cardiff Metropolitan University (UK)", "BSc (Hons) Business & Management Studies - Cardiff Metropolitan University (UK)", "BSc (Hons) Software Engineering - Cardiff Metropolitan University (UK)", "Bsc(Hons) Information Technology - Cardiff Metropolitan University (UK)", "BEng( Hons) Biomedical Engineering- Birmingham City University", "BEng(Hons) Mechatronics Engineering- Birmingham City University", "BSc (Hons) Civil and Structural Engineering - Liverpool John Moores University (UK)", "BEng (Hons) Electronic and Electrical Engineering - University of Sunderland (UK)", "BEng (Hons) Mechanical Engineering - University of Sunderland (UK)", "BEng (Hons) Automotive Engineering - University of Sunderland (UK)", "BSc(Hons)Nursing - University of Sunderland (UK)", "BSc (Hons) in Quantity Surveying", "BSc (Hons) in Computer Networks", "ICBT HND in Computer Networks" }));
        jPanel4.add(jCombocourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 270, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 204));
        jLabel22.setText("Duration");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 210, 30));

        jComboduration1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "2 Years part time", "2 Years Full time" }));
        jPanel4.add(jComboduration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 270, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 204));
        jLabel21.setText("Batch");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 210, 30));
        jPanel4.add(batch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 30, 30));

        jCombobatch1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Sunday 8.00 am to 5.00 pm", "Saturday  8.00 am to 5.00 pm", "Weekdays 8.00 am to 5.00 pm(Full time Students Only)" }));
        jPanel4.add(jCombobatch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 230, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Course Fee");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 210, 30));
        jPanel4.add(ugraduatefee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 270, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("To search or delete individual enrollment type the student number in student uni id field");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 540, -1));

        jButton3save.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton3save.setForeground(new java.awt.Color(0, 102, 204));
        jButton3save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Save-as-icon.png"))); // NOI18N
        jButton3save.setText("Save");
        jButton3save.setAutoscrolls(true);
        jButton3save.setOpaque(false);
        jButton3save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3saveActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Actions-edit-clear-icon.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 250, 90));

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 204));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Close-2-icon.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 250, 90));

        jTabbedPane1.addTab("Under Graduate Program", jPanel4);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1110, 480));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1150, 130));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3saveActionPerformed
        if (studentid1.getText().isEmpty()|nic1.getText().isEmpty()|fullname1.getText().isEmpty()|initial1.getText().isEmpty()|jCombocourse1.getSelectedItem().equals("None")|jComboduration1.getSelectedItem().equals("None")|batch1.getText().isEmpty()|jCombobatch1.getSelectedItem().equals("None")|ugraduatefee1.getText().isEmpty()) {
            
                 getToolkit().beep();
                JOptionPane.showMessageDialog(null,"One of the required field is empty","ERROR",JOptionPane.ERROR_MESSAGE,null);
        }
       else if (!nic1.getText().trim().matches("^[0-9]{9}[vVxX]$")) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Invalid Nic!","ERROR",JOptionPane.ERROR_MESSAGE,null);
            }
        else{
                try {
            
            
            String query = "INSERT INTO courseunder (nic,studentid,fullname,initials,course,duration,batchno,day,coursefee) values(?,?,?,?,?,?,?,?,?)";
            String query1 = "SELECT * FROM courseposter WHERE nic=?";
            PreparedStatement pst1 = con.prepareStatement(query1);
            pst1.setString(1, nic1.getText());
            ResultSet rs = pst1.executeQuery();
            if (rs.next()) {
                
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"This student has already enrolled for a Poster Graduate Program","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            
            }
            else{
            
            
            PreparedStatement pst = con.prepareStatement(query);
            
           
           
            
            pst.setString(1, nic1.getText());
            pst.setString(2, studentid1.getText());
            pst.setString(3, fullname1.getText());
            pst.setString(4, initial1.getText());
            pst.setString(5, jCombocourse1.getSelectedItem().toString());
            pst.setString(6, jComboduration1.getSelectedItem().toString());
          
            pst.setString(7, batch1.getText());
            pst.setString(8, jCombobatch1.getSelectedItem().toString());
            pst.setString(9, ugraduatefee1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Saved Successfully");
            
            
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        }

    }//GEN-LAST:event_jButton3saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (studentid1.getText().isEmpty()|nic1.getText().isEmpty()|fullname1.getText().isEmpty()|initial1.getText().isEmpty()|jCombocourse1.getSelectedItem().equals("None")|jComboduration1.getSelectedItem().equals("None")|batch1.getText().isEmpty()|jCombobatch1.getSelectedItem().equals("None")|ugraduatefee1.getText().isEmpty()) {
            getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Specify What Data You Want To Update","ERROR",JOptionPane.ERROR_MESSAGE,null);
        }

        else{
        try {
            

            String value=nic1.getText();
            String query = "UPDATE courseunder SET studentid=?,fullname=?,initials=?,course=?,duration=?,batchno=?,day=?,coursefee=? WHERE nic='"+value+"'";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, studentid1.getText());
            pst.setString(2, fullname1.getText());
            pst.setString(3, initial1.getText());

            pst.setString(4, jCombocourse1.getSelectedItem().toString());
            pst.setString(5, jComboduration1.getSelectedItem().toString());
           
            pst.setString(6, batch1.getText());
             pst.setString(7, jCombobatch1.getSelectedItem().toString());
            pst.setString(8, ugraduatefee1.getText());
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased

        try {
           
            String query = "SELECT * FROM student WHERE nic=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nic.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("fullname");
                fullname.setText(add1);
                String add2 = rs.getString("initial");
                initial.setText(add2);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_nicKeyReleased

    private void nic1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic1KeyReleased
try {
           
            String query = "SELECT * FROM student WHERE nic=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nic1.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("fullname");
                fullname1.setText(add1);
                String add2 = rs.getString("initial");
                initial1.setText(add2);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
    }//GEN-LAST:event_nic1KeyReleased

    private void studentid1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentid1KeyReleased
       try {
            
            String query = "SELECT * FROM courseunder WHERE studentid=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, studentid1.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("nic");
                nic1.setText(add1);
                String add2 = rs.getString("fullname");
                fullname1.setText(add2);
                String add3 = rs.getString("initials");
                initial1.setText(add3);
                String add4 = rs.getString("course");
                jCombocourse1.setSelectedItem(add4);
                String add5 = rs.getString("duration");
                jComboduration1.setSelectedItem(add5);
                String add6 = rs.getString("batchno");
                batch1.setText(add6);
                String add7 = rs.getString("day");
                jCombobatch1.setSelectedItem(add7);
                String add8 = rs.getString("coursefee");
                ugraduatefee1.setText(add8);
            
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_studentid1KeyReleased

    private void jButton3save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3save1ActionPerformed
      try {
          
           
            String query = "INSERT INTO courseposter(nic,studentid,fullname,initials,course,duration,batchno,day,coursefee) values(?,?,?,?,?,?,?,?,?)";
            String query1 = "SELECT * FROM courseunder WHERE nic=?";
            PreparedStatement pst1 = con.prepareStatement(query1);
            pst1.setString(1, nic.getText());
            ResultSet rs = pst1.executeQuery();
            if (rs.next()) {
                
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"This student has already enrolled for a Poster Graduate Program","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            
            }
            
            
            
              
            PreparedStatement pst = con.prepareStatement(query);
            
            
             if (nic.getText().isEmpty() | studentid.getText().isEmpty()| fullname.getText().isEmpty()|initial.getText().isEmpty()|jCombocourse.getSelectedItem().toString().equals("None")|jComboduration.getSelectedItem().toString().equals("None")|batch.getText().isEmpty()||jCombobatch.getSelectedItem().equals("None")) {
               
                 getToolkit().beep();
                JOptionPane.showMessageDialog(null,"One of the required field is empty","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            }
             
             else if (!nic.getText().trim().matches("^[0-9]{9}[vVxX]$")) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Invalid Nic!","ERROR",JOptionPane.ERROR_MESSAGE,null);
            }
             
             
             
             
             else{
            pst.setString(1, nic.getText()); 
            pst.setString(2, studentid.getText());
            pst.setString(3, fullname.getText());
            pst.setString(4, initial.getText());
            pst.setString(5, jCombocourse.getSelectedItem().toString());
            pst.setString(6, jComboduration.getSelectedItem().toString());
          
            pst.setString(7, batch.getText());
            pst.setString(8, jCombobatch.getSelectedItem().toString());
            pst.setString(9, ugraduatefee.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Saved Successfully");
             }
            
            
            
            
            
            
            
            
           
          
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3save1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (nic.getText().isEmpty() | studentid.getText().isEmpty()| fullname.getText().isEmpty()|initial.getText().isEmpty()|jCombocourse.getSelectedItem().toString().equals("None")|jComboduration.getSelectedItem().toString().equals("None")|batch.getText().isEmpty()||jCombobatch.getSelectedItem().equals("None")) {
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Specify What Data You Want To Update","ERROR",JOptionPane.ERROR_MESSAGE,null);
        }
        else{
        try {
          
            String value=nic.getText();
            String query = "UPDATE courseposter SET studentid=?,fullname=?,initials=?,course=?,duration=?,batchno=?,day=?,coursefee=? WHERE nic='"+value+"'";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, studentid.getText());
            pst.setString(2, fullname.getText());
            pst.setString(3, initial.getText());

            pst.setString(4, jCombocourse.getSelectedItem().toString());
            pst.setString(5, jComboduration.getSelectedItem().toString());
           
            pst.setString(6, batch.getText());
             pst.setString(7, jCombobatch.getSelectedItem().toString());
            pst.setString(8, ugraduatefee.getText());
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         
        if (studentid.getText().isEmpty()) {
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Enter the Studentid in the Studentid Field to Delete Data","ERROR",JOptionPane.ERROR_MESSAGE,null);
            
        }
        else{
        try {
             int p= JOptionPane.showConfirmDialog(null, "Do You Want To Delete The Student "+fullname.getText()+" From The Database","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0) {
          
            String query = "DELETE FROM courseposter WHERE nic=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nic.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "data successfully deleted");
        }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void studentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentidKeyReleased
  try {
          
            String query = "SELECT * FROM courseposter WHERE studentid=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, studentid.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("nic");
                nic.setText(add1);
                String add2 = rs.getString("fullname");
                fullname.setText(add2);
                String add3 = rs.getString("initials");
                initial.setText(add3);
                String add4 = rs.getString("course");
                jCombocourse.setSelectedItem(add4);
                String add5 = rs.getString("duration");
                jComboduration.setSelectedItem(add5);
                String add6 = rs.getString("batchno");
                batch.setText(add6);
                String add7 = rs.getString("day");
                jCombobatch.setSelectedItem(add7);
                String add8 = rs.getString("coursefee");
                ugraduatefee.setText(add8);
            
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
        
    }//GEN-LAST:event_studentidKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         if (studentid1.getText().isEmpty()) {
            getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Enter the Studentid in the Studentid Field to Delete Data","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
        } else{
        
        try {
             int p= JOptionPane.showConfirmDialog(null, "Do You Want To Delete The Student "+fullname1.getText()+" From The Database","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0) {
           
            String query = "DELETE FROM courseunder WHERE studentit=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, studentid.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "data successfully deleted");
        }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
         }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void nic1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic1KeyTyped
 String s=nic1.getText();
            
            if (!(s.length()<10 ))
            {
                
                    evt.consume();
                      getToolkit().beep();
            
            }      
       
        
        
    }//GEN-LAST:event_nic1KeyTyped

    private void nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyTyped
          String s=nic.getText();
            
            if (!(s.length()<10 ))
            {
                
                    evt.consume();
                      getToolkit().beep();
            
            }
    }//GEN-LAST:event_nicKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batch;
    private javax.swing.JTextField batch1;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField fullname1;
    private javax.swing.JTextField initial;
    private javax.swing.JTextField initial1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3save;
    private javax.swing.JButton jButton3save1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jCombobatch;
    private javax.swing.JComboBox<String> jCombobatch1;
    private javax.swing.JComboBox<String> jCombocourse;
    private javax.swing.JComboBox<String> jCombocourse1;
    private javax.swing.JComboBox<String> jComboduration;
    private javax.swing.JComboBox<String> jComboduration1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField nic1;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField studentid1;
    private javax.swing.JTextField ugraduatefee;
    private javax.swing.JTextField ugraduatefee1;
    // End of variables declaration//GEN-END:variables
}
